### ISSUE TITLE
Quandl API key

### ISSUE THREAD

**Issue by stoltzmaniac** [focods/neural-net-stock-trading#2]
Kevin - your API key location is hard coded. Can you adjust this to pull from a directory that is relative to the folder this is in?

We also need to know how to get the key / download the yaml file.

**Comment by kevinmcmanus** [comment]
Now gets the yaml file from current directory. Includes (cryptic) instructions as to how to put the API key in the yaml file; also has provision for just pasting in the api key directly in the notebook.  Includes instructions on getting the quandl library as well as a pointer to obtain the quandl api key from quandl. Fixed in the 'crossover' commit.
